[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./test" }, { access = "read-write", path = "./script/output" }, { access = "read", path = "./config/avs.json" }]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.25"
evm_version = "cancun"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
local = "http://localhost:8545"
holesky = "https://rpc.holesky.ethpandaops.io"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
holesky = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
